2024-11-16 13:54:30 - HypercubeAnalysis - INFO - Event: analysis_start
2024-11-16 13:54:30 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:31 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:31 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:31 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:31 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:32 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:32 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:32 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:32 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:33 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:33 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:33 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:33 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:34 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:34 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:35 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:35 - HypercubeAnalysis - INFO - Event: iteration_start
2024-11-16 13:54:35 - HypercubeAnalysis - INFO - Event: iteration_complete
2024-11-16 13:54:35 - HypercubeAnalysis - ERROR - Error occurred with context
2024-11-16 13:54:35 - HypercubeAnalysis - ERROR - Uncaught exception:
Traceback (most recent call last):
  File "d:\Github\larsonPaperReplication\main.py", line 250, in <module>
    main()
  File "d:\Github\larsonPaperReplication\main.py", line 239, in main
    analysis.run_paper_replication()
  File "d:\Github\larsonPaperReplication\main.py", line 86, in run_paper_replication
    self._generate_comparisons()
  File "d:\Github\larsonPaperReplication\main.py", line 132, in _generate_comparisons
    self.results['comparisons'] = comparator.compare_queue_types(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Github\larsonPaperReplication\src\analysis\comparison.py", line 56, in compare_queue_types
    zero_line['workloads'],
    ~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'workloads'
